<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(BuildToolTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>J2N.Tools.GenerateUnicodeData</RootNamespace>
    <IsPackable>false</IsPackable>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>

</Project>
