<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup Label="Assembly Publishing">
    <IsPublishable>true</IsPublishable>
  </PropertyGroup>
  
  <PropertyGroup Label="Skip Building Tests During Build" Condition="'$(BuildGroup)' == 'LibrariesOnly' ">

    <!-- Prevents the project from being restored -->
    <RestoreTargets>$(MSBuildThisFileDirectory)Empty.targets</RestoreTargets>
    <NuGetAudit>false</NuGetAudit>
    
    <!-- Stops this project from building its own dependencies -->
    <BuildProjectReferences>false</BuildProjectReferences>

  </PropertyGroup>

</Project>