using J2N.Text.CodeGen.Metadata;
using J2N.Text.CodeGen.Projection;
using System.Text;

namespace J2N.Text.CodeGen.Generation
{
    public sealed class CSharpExtensionEmitter
    {
        public string Emit(
            ProjectedTypeModel model,
            ExtensionEmitterOptions? options = null)
        {
            options ??= new ExtensionEmitterOptions();

            bool wrapMembersInLock = options.WrapMembersInLock;

            var sb = new StringBuilder();

            EmitHeader(sb);

            EmitUsings(sb, model.Source.Usings);

            sb.AppendLine();

            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");

            sb.AppendLine($"    public static partial class {model.Name}");
            sb.AppendLine("    {");

            string? activeConditional = null;

            foreach (MethodModel method in model.Methods)
            {
                if (method.ConditionalCompilationSymbol
                    != activeConditional)
                {
                    if (activeConditional is not null)
                    {
                        sb.AppendLine("#endif");
                        sb.AppendLine();
                    }

                    activeConditional =
                        method.ConditionalCompilationSymbol;

                    if (activeConditional is not null)
                    {
                        sb.AppendLine($"#if {activeConditional}");
                    }
                }

                EmitMethod(sb, method, wrapMembersInLock);
            }

            if (activeConditional is not null)
            {
                sb.AppendLine("#endif");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitHeader(
            StringBuilder sb)
        {
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by a tool.");
            sb.AppendLine("//");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("//");
            sb.AppendLine("//     Instead of editing this file, the MutableTextBufferExtensions*.cs files should be edited");
            sb.AppendLine("//     which will propagate the edits to this file.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");

            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS1591 // J2N TODO: Finish docs");
            sb.AppendLine();
        }

        private static void EmitUsings(
            StringBuilder sb,
            IEnumerable<string> usings)
        {
            foreach (string ns in usings.Distinct())
            {
                sb.AppendLine($"using {ns};");
            }
        }

        private static void EmitMethod(
            StringBuilder sb,
            MethodModel method,
            bool wrapMembersInLock)
        {
            CSharpDocumentationEmitter.EmitDocumentation(
                sb,
                method.Documentation);

            EmitAttributes(
                sb,
                method.Attributes);

            string unsafeModifier =
                method.IsUnsafe
                    ? " unsafe"
                    : "";

            string parameterList =
                string.Join(
                    ", ",
                    method.Parameters.Select(FormatParameter));

            string genericParameters =
                method.GenericParameters.Count > 0
                    ? "<" + string.Join(", ",
                        method.GenericParameters.Select(p => p.Name)) + ">"
                    : "";

            bool shouldWrapInLock =
                wrapMembersInLock
                && !method.SkipSynchronization;

            sb.AppendLine(
                $"        public static{unsafeModifier} {method.ReturnType} {method.Name}{genericParameters}({parameterList})");

            EmitConstraints(
                sb,
                method.GenericParameters);

            if (method.GenerateForwarder)
            {
                EmitForwarder(sb, method, shouldWrapInLock);
            }
            else
            {

                // BodyText currently cannot be combined with shouldWrapInLock
                EmitBodyText(sb, method);
            }

            sb.AppendLine();
        }

        private static string FormatParameter(ParameterModel parameter)
        {
            string modifier =
                string.IsNullOrWhiteSpace(parameter.Modifier)
                    ? ""
                    : parameter.Modifier + " ";

            string defaultValue =
                parameter.DefaultValueExpression is null
                    ? ""
                    : $" = {parameter.DefaultValueExpression}";

            return
                $"{modifier}{parameter.TypeName} {parameter.Name}{defaultValue}";
        }

        private static void EmitConstraints(
            StringBuilder sb,
            IEnumerable<GenericParameterModel> genericParameters)
        {
            foreach (GenericParameterModel parameter in genericParameters)
            {
                if (parameter.Constraints.Count == 0)
                    continue;

                sb.AppendLine(
                    $"            where {parameter.Name} : {string.Join(", ", parameter.Constraints)}");
            }
        }

        private static void EmitAttributes(
            StringBuilder sb,
            IEnumerable<AttributeModel> attributes,
            string indent = "        ")
        {
            foreach (AttributeModel attribute in attributes
                .Where(a =>
                    !a.Name.StartsWith("CodeGeneration", StringComparison.Ordinal)))
            {
                if (attribute.Arguments.Count == 0)
                {
                    sb.AppendLine($"{indent}[{attribute.Name}]");
                }
                else
                {
                    string args = string.Join(", ", attribute.Arguments);

                    sb.AppendLine($"{indent}[{attribute.Name}({args})]");
                }
            }
        }

        private static void EmitBodyText(
            StringBuilder sb,
            MethodModel method)
        {
            //
            // BodyText already contains properly formatted code.
            // Just emit it exactly as-is, preserving indentation.
            //

            if (!string.IsNullOrWhiteSpace(method.BodyText))
            {
                string normalized =
                    method.BodyText.Replace("\r\n", "\n")
                                   .Replace('\r', '\n');

                string[] lines =
                    normalized.Split('\n');

                // Remove leading/trailing blank lines
                int start = 0;
                int end = lines.Length - 1;

                while (start <= end && string.IsNullOrWhiteSpace(lines[start]))
                    start++;

                while (end >= start && string.IsNullOrWhiteSpace(lines[end]))
                    end--;

                for (int i = start; i <= end; i++)
                {
                    sb.AppendLine(lines[i]);
                }
            }
            else
            {
                sb.AppendLine("        {");
                sb.AppendLine("            throw new NotImplementedException();");
                sb.AppendLine("        }");
            }
        }

        private static void EmitForwarder(
            StringBuilder sb,
            MethodModel method,
            bool shouldWrapInLock)
        {
            string argumentList =
                string.Join(
                    ", ",
                    method.Parameters.Skip(1).Select(
                        p => p.Name));

            string extensionParameterName =
                method.Parameters.FirstOrDefault()?.Name ?? "text";


            sb.AppendLine("        {");

            sb.AppendLine($"            if ({extensionParameterName} is null)");
            sb.AppendLine($"                throw new ArgumentNullException(nameof({extensionParameterName}));");
            sb.AppendLine();

            if (shouldWrapInLock)
            {
                sb.AppendLine($"            lock ({extensionParameterName}.SyncRoot)");
                sb.AppendLine("            {");

                if (string.IsNullOrEmpty(method.ForwardTargetObject))
                {
                    sb.AppendLine($"                {extensionParameterName}.{method.ForwardTarget}({argumentList});");
                }
                else
                {
                    sb.AppendLine($"                {extensionParameterName}.{method.ForwardTargetObject}.{method.ForwardTarget}({argumentList});");
                }

                sb.AppendLine($"                return {extensionParameterName};");
                sb.AppendLine("            }");
            }
            else
            {
                if (string.IsNullOrEmpty(method.ForwardTargetObject))
                {
                    sb.AppendLine($"            {extensionParameterName}.{method.ForwardTarget}({argumentList});");
                }
                else
                {
                    sb.AppendLine($"            {extensionParameterName}.{method.ForwardTargetObject}.{method.ForwardTarget}({argumentList});");
                }

                sb.AppendLine($"            return {extensionParameterName};");
            }

            sb.AppendLine("        }");
        }
    }
}
