using J2N.Text.CodeGen.Metadata;
using J2N.Text.CodeGen.Projection;
using System.Linq;
using System.Text;

namespace J2N.Text.CodeGen.Generation
{
    public sealed class CSharpFacadeEmitter
    {
        public string EmitFacade(
            ProjectedTypeModel model,
            string backingFieldName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();

            foreach (string @using in model.Source.Usings.Distinct())
            {
                sb.AppendLine($"using {@using};");
            }

            sb.AppendLine();

            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine();

            sb.AppendLine($"    public partial class {model.Name}");
            sb.AppendLine("    {");

            foreach (MethodModel method in model.Methods)
            {
                EmitDocumentation(sb, method.Documentation, method.Parameters);
                EmitMethod(sb, method, model.Name, backingFieldName);
            }

            foreach (PropertyModel property in model.Properties)
            {
                EmitDocumentation(sb, property.Documentation, property.IndexParameters);
                EmitProperty(sb, property, backingFieldName);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitMethod(
            StringBuilder sb,
            MethodModel method,
            string facadeName,
            string backingFieldName)
        {
            string parameterList =
                string.Join(
                    ", ",
                    method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));

            string argumentList =
                string.Join(
                    ", ",
                    method.Parameters.Select(p => p.Name));

            string returnType =
                method.ReturnsSelf
                    ? facadeName
                    : method.ReturnType;

            sb.AppendLine($"        public {returnType} {method.Name}({parameterList})");
            sb.AppendLine("        {");

            if (method.IsBuilderMethod && method.ReturnsSelf)
            {
                sb.AppendLine($"            {backingFieldName}.{method.Name}({argumentList});");
                sb.AppendLine("            return this;");
            }
            else if (method.ReturnType == "void")
            {
                sb.AppendLine($"            {backingFieldName}.{method.Name}({argumentList});");
            }
            else
            {
                sb.AppendLine($"            return {backingFieldName}.{method.Name}({argumentList});");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitProperty(
            StringBuilder sb,
            PropertyModel property,
            string backingFieldName)
        {
            if (!property.IsIndexer)
            {
                sb.AppendLine($"        public {property.TypeName} {property.Name}");
                sb.AppendLine("        {");

                if (property.HasGetter)
                {
                    sb.AppendLine($"            get => {backingFieldName}.{property.Name};");
                }

                if (property.HasSetter)
                {
                    sb.AppendLine($"            set => {backingFieldName}.{property.Name} = value;");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            // Indexer
            string indexParams =
                string.Join(", ",
                    property.IndexParameters.Select(p => $"{p.TypeName} {p.Name}"));

            string args =
                string.Join(", ",
                    property.IndexParameters.Select(p => p.Name));

            sb.AppendLine($"        public {property.TypeName} this[{indexParams}]");
            sb.AppendLine("        {");

            if (property.HasGetter)
            {
                sb.AppendLine($"            get => {backingFieldName}[{args}];");
            }

            if (property.HasSetter)
            {
                sb.AppendLine($"            set => {backingFieldName}[{args}] = value;");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitDocumentation(
            StringBuilder sb,
            DocumentationModel? docs,
            IEnumerable<ParameterModel> parameters)
        {
            if (docs is null && !parameters.Any())
                return;

            if (!string.IsNullOrWhiteSpace(docs?.Summary))
            {
                sb.AppendLine("        /// <summary>");

                foreach (string line in docs.Summary.Split('\n'))
                {
                    sb.AppendLine($"        /// {line.Trim()}");
                }

                sb.AppendLine("        /// </summary>");
            }

            foreach (ParameterModel parameter in parameters)
            {
                if (!string.IsNullOrWhiteSpace(parameter.Documentation))
                {
                    sb.AppendLine(
                        $"        /// <param name=\"{parameter.Name}\">{parameter.Documentation}</param>");
                }
            }

            if (!string.IsNullOrWhiteSpace(docs?.Returns))
            {
                sb.AppendLine(
                    $"        /// <returns>{docs.Returns}</returns>");
            }

            if (!string.IsNullOrWhiteSpace(docs?.Remarks))
            {
                sb.AppendLine("        /// <remarks>");

                foreach (string line in docs.Remarks.Split('\n'))
                {
                    sb.AppendLine($"        /// {line.Trim()}");
                }

                sb.AppendLine("        /// </remarks>");
            }
        }
    }
}
