using J2N.Text.CodeGen.Metadata;
using J2N.Text.CodeGen.Projection;
using System.Linq;
using System.Text;

namespace J2N.Text.CodeGen.Generation
{
    public sealed class CSharpFacadeEmitter
    {
        public string EmitFacade(
            ProjectedTypeModel model,
            string backingFieldName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            foreach (string @using in model.Source.Usings.Distinct())
            {
                sb.AppendLine($"using {@using};");
            }

            sb.AppendLine();

            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine();

            sb.AppendLine($"    public partial class {model.Name}");
            sb.AppendLine("    {");

            foreach (PropertyModel property in model.Properties)
            {
                EmitDocumentation(sb, property.Documentation, property.IndexParameters);
                EmitAttributes(sb, property.Attributes, "        ");
                EmitProperty(sb, property, backingFieldName);
            }

            foreach (MethodModel method in model.Methods)
            {
                EmitDocumentation(sb, method.Documentation, method.Parameters);
                EmitAttributes(sb, method.Attributes, "        ");
                EmitMethod(sb, method, model.Name, backingFieldName);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitMethod(
            StringBuilder sb,
            MethodModel method,
            string facadeName,
            string backingFieldName)
        {
            string parameterList =
                string.Join(
                    ", ",
                    method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));

            string genericParameterList =
                method.GenericParameters.Count == 0
                    ? ""
                    : "<" + string.Join(", ", method.GenericParameters.Select(p => p.Name)) + ">";

            string argumentList =
                string.Join(
                    ", ",
                    method.Parameters.Select(p => p.Name));

            string returnType =
                method.ReturnsSelf
                    ? facadeName
                    : method.ReturnType;

            string unsafeModifier = method.IsUnsafe ? " unsafe" : "";
            string modifier = IsObjectMethod(method) ? " override" : "";

            sb.AppendLine($"        public{modifier}{unsafeModifier} {returnType} {method.Name}{genericParameterList}({parameterList})");
            foreach (GenericParameterModel parameter in method.GenericParameters)
            {
                if (parameter.Constraints.Count == 0)
                {
                    continue;
                }

                sb.Append("            where ");
                sb.Append(parameter.Name);
                sb.Append(" : ");
                sb.AppendLine(string.Join(", ", parameter.Constraints));
            }
            sb.AppendLine("        {");

            if (method.IsBuilderMethod && method.ReturnsSelf)
            {
                sb.AppendLine($"            {backingFieldName}.{method.Name}({argumentList});");
                sb.AppendLine("            return this;");
            }
            else if (method.ReturnType == "void")
            {
                sb.AppendLine($"            {backingFieldName}.{method.Name}({argumentList});");
            }
            else
            {
                sb.AppendLine($"            return {backingFieldName}.{method.Name}({argumentList});");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitProperty(
            StringBuilder sb,
            PropertyModel property,
            string backingFieldName)
        {
            string unsafeModifier = property.IsUnsafe ? " unsafe" : "";

            if (!property.IsIndexer)
            {
                sb.AppendLine($"        public{unsafeModifier} {property.TypeName} {property.Name}");
                sb.AppendLine("        {");

                if (property.HasGetter)
                {
                    sb.AppendLine($"            get => {backingFieldName}.{property.Name};");
                }

                if (property.HasSetter)
                {
                    sb.AppendLine($"            set => {backingFieldName}.{property.Name} = value;");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
                return;
            }

            // Indexer
            string indexParams =
                string.Join(", ",
                    property.IndexParameters.Select(p => $"{p.TypeName} {p.Name}"));

            string args =
                string.Join(", ",
                    property.IndexParameters.Select(p => p.Name));

            sb.AppendLine($"        public{unsafeModifier} {property.TypeName} this[{indexParams}]");
            sb.AppendLine("        {");

            if (property.HasGetter)
            {
                sb.AppendLine($"            get => {backingFieldName}[{args}];");
            }

            if (property.HasSetter)
            {
                sb.AppendLine($"            set => {backingFieldName}[{args}] = value;");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitAttributes(
            StringBuilder sb,
            IEnumerable<AttributeModel> attributes,
            string indent)
        {
            foreach (AttributeModel attribute in attributes)
            {
                if (attribute.Arguments.Count == 0)
                {
                    sb.AppendLine($"{indent}[{attribute.Name}]");
                }
                else
                {
                    string args = string.Join(", ", attribute.Arguments);

                    sb.AppendLine($"{indent}[{attribute.Name}({args})]");
                }
            }
        }

        private static void EmitDocumentation(
            StringBuilder sb,
            DocumentationModel? docs,
            IEnumerable<ParameterModel> parameters)
        {
            if (docs is null && !parameters.Any())
                return;

            EmitXmlElement(sb, "summary", docs?.SummaryXml);

            foreach (ParameterModel parameter in parameters)
            {
                EmitParamDocumentation(sb, parameter);
            }

            EmitXmlElement(sb, "returns", docs?.ReturnsXml);

            EmitXmlElement(sb, "remarks", docs?.RemarksXml);
        }

        private static void EmitParamDocumentation(
            StringBuilder sb,
            ParameterModel parameter)
        {
            if (string.IsNullOrWhiteSpace(parameter.Documentation))
                return;

            sb.AppendLine($"        /// <param name=\"{parameter.Name}\">");

            foreach (string line in parameter.Documentation.Split('\n'))
            {
                sb.AppendLine($"        /// {line.TrimEnd()}");
            }

            sb.AppendLine("        /// </param>");
        }

        private static void EmitXmlElement(
            StringBuilder sb,
            string elementName,
            string? content)
        {
            if (string.IsNullOrWhiteSpace(content))
                return;

            sb.AppendLine($"        /// <{elementName}>");

            foreach (string line in content.Split('\n'))
            {
                sb.AppendLine($"        /// {line.TrimEnd()}");
            }

            sb.AppendLine($"        /// </{elementName}>");
        }

        private static bool IsObjectMethod(MethodModel method)
        {
            if (method.Name == "ToString"
                && method.Parameters.Count == 0)
            {
                return true;
            }

            if (method.Name == "GetHashCode"
                && method.Parameters.Count == 0)
            {
                return true;
            }

            if (method.Name == "Equals"
                && method.Parameters.Count == 1 && (method.Parameters[0].TypeName == "object?" || method.Parameters[0].TypeName == "object"))
            {
                return true;
            }

            return false;
        }
    }
}
