using J2N.Text.CodeGen.Metadata;
using J2N.Text.CodeGen.Projection;
using System.Linq;
using System.Text;

namespace J2N.Text.CodeGen.Generation
{
    public sealed class CSharpFacadeEmitter
    {
        public string EmitFacade(
            ProjectedTypeModel model,
            string backingFieldName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();

            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine();

            sb.AppendLine($"    public partial class {model.Name}");
            sb.AppendLine("    {");

            foreach (MethodModel method in model.Methods)
            {
                EmitMethod(sb, method, model.Name, backingFieldName);
            }

            foreach (PropertyModel property in model.Properties)
            {
                EmitProperty(sb, property, model.Name, backingFieldName);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitMethod(
            StringBuilder sb,
            MethodModel method,
            string facadeName,
            string backingFieldName)
        {
            string parameterList =
                string.Join(
                    ", ",
                    method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));

            string argumentList =
                string.Join(
                    ", ",
                    method.Parameters.Select(p => p.Name));

            string returnType =
                method.ReturnsSelf
                    ? facadeName
                    : method.ReturnType;

            sb.AppendLine($"        public {returnType} {method.Name}({parameterList})");
            sb.AppendLine("        {");

            if (method.ReturnsSelf)
            {
                sb.AppendLine($"            {backingFieldName}.{method.Name}({argumentList});");
                sb.AppendLine("            return this;");
            }
            else if (method.ReturnType == "void")
            {
                sb.AppendLine($"            {backingFieldName}.{method.Name}({argumentList});");
            }
            else
            {
                sb.AppendLine($"            return {backingFieldName}.{method.Name}({argumentList});");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitProperty(
            StringBuilder sb,
            PropertyModel property,
            string facadeName,
            string backingFieldName)
        {
            string type = property.TypeName;

            sb.AppendLine($"        public {type} {property.Name}");
            sb.AppendLine("        {");

            if (property.HasGetter)
            {
                if (property.IsIndexer)
                {
                    string args = string.Join(", ", property.IndexParameters.Select(p => p.Name));
                    sb.AppendLine($"            get => {backingFieldName}[{args}];");
                }
                else
                {
                    sb.AppendLine($"            get => {backingFieldName}.{property.Name};");
                }
            }

            if (property.HasSetter)
            {
                if (property.IsIndexer)
                {
                    string args = string.Join(", ", property.IndexParameters.Select(p => p.Name));
                    sb.AppendLine($"            set => {backingFieldName}[{args}] = value;");
                }
                else
                {
                    sb.AppendLine($"            set => {backingFieldName}.{property.Name} = value;");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
