//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     Instead of editing this file, the MutableTextBufferExtensions*.cs files should be edited
//     which will propagate the edits to this file.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using J2N.CodeGeneration;
using J2N.Numerics;
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace J2N.Text
{
    public static partial class PooledTextBuilderExtensions
    {
        /// <summary>
        /// 
        /// Creates a new readonly span over the portion of the target string.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <returns>
        /// The read-only span representation of the string.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned span is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the span contents.
        /// 
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ReadOnlySpan<char> AsSpan(this PooledTextBuilder? text)
        {
            if (text is null)
                return default;

#if FEATURE_MEMORYMARSHAL_CREATEREADONLYSPAN && FEATURE_MEMORYMARSHAL_GETARRAYDATAREFERENCE
            // J2N: Careful - need to create a local copy because it could move.
            char[] chars = text.buffer.m_Chars;
            return MemoryMarshal.CreateReadOnlySpan<char>(ref MemoryMarshal.GetArrayDataReference(chars), text.Length);
#else
            return new ReadOnlySpan<char>(text.buffer.m_Chars, 0, text.Length);
#endif
        }

        /// <summary>
        /// 
        /// Creates a new read-only span over a portion of the target string from
        /// a specified position to the end of the string.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <param name="start">
        /// The index at which to begin this slice.
        /// </param>
        /// <returns>
        /// The read-only span representation of the string.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned span is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the span contents.
        /// 
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ReadOnlySpan<char> AsSpan(this PooledTextBuilder? text, int start)
        {
            if (text == null)
            {
                if (start != 0)
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
                return default;
            }

            if ((uint)start > (uint)text.Length)
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);

#if FEATURE_MEMORYMARSHAL_CREATEREADONLYSPAN && FEATURE_MEMORYMARSHAL_GETARRAYDATAREFERENCE
            // J2N: Careful - need to create a local copy because it could move.
            char[] chars = text.buffer.m_Chars;
            return MemoryMarshal.CreateReadOnlySpan<char>(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(chars),
                (nint)(uint)start /* force zero-extension */), text.Length - start);
#else
            return new ReadOnlySpan<char>(text.buffer.m_Chars, start, text.Length - start);
#endif
        }

        /// <summary>
        /// 
        /// Creates a new read-only span over a portion of the target string from a
        /// specified position for a specified number of characters.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <param name="start">
        /// The index at which to begin this slice.
        /// </param>
        /// <param name="length">
        /// The desired length for the slice.
        /// </param>
        /// <returns>
        /// The read-only span representation of the string.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned span is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the span contents.
        /// 
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ReadOnlySpan<char> AsSpan(this PooledTextBuilder? text, int start, int length)
        {
            if (text == null)
            {
                if (start != 0 || length != 0)
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
                return default;
            }

            if (IntPtr.Size == 8) // 64-bit process
            {
                // See comment in Span<T>.Slice for how this works.
                if ((ulong)(uint)start + (ulong)(uint)length > (ulong)(uint)text.Length)
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
            }
            else
            {
                if ((uint)start > (uint)text.Length || (uint)length > (uint)(text.Length - start))
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
            }

#if FEATURE_MEMORYMARSHAL_CREATEREADONLYSPAN && FEATURE_MEMORYMARSHAL_GETARRAYDATAREFERENCE
            // J2N: Careful - need to create a local copy because it could move.
            char[] chars = text.buffer.m_Chars;
            return MemoryMarshal.CreateReadOnlySpan<char>(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(chars),
                (nint)(uint)start /* force zero-extension */), length);
#else
            return new ReadOnlySpan<char>(text.buffer.m_Chars, start, length);
#endif
        }

#if FEATURE_INDEX_RANGE
        /// <summary>
        /// 
        /// Creates a new read-only span over a portion of the
        /// target string from a specified position to the end of the string.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <param name="startIndex">
        /// The index at which to begin this slice.
        /// </param>
        /// <returns>
        /// The read-only span representation of the string.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned span is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the span contents.
        /// 
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ReadOnlySpan<char> AsSpan(this PooledTextBuilder? text, Index startIndex)
        {
            if (text is null)
            {
                if (!startIndex.Equals(Index.Start))
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startIndex);
                }

                return default;
            }

            int actualIndex = startIndex.GetOffset(text.Length);
            if ((uint)actualIndex > (uint)text.Length)
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startIndex);
            }

#if FEATURE_MEMORYMARSHAL_CREATEREADONLYSPAN && FEATURE_MEMORYMARSHAL_GETARRAYDATAREFERENCE
            // J2N: Careful - need to create a local copy because it could move.
            char[] chars = text.buffer.m_Chars;
            return MemoryMarshal.CreateReadOnlySpan<char>(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(chars),
                (nint)(uint)actualIndex /* force zero-extension */), text.Length - actualIndex);
#else
            return new ReadOnlySpan<char>(text.buffer.m_Chars, actualIndex, text.Length - actualIndex);
#endif
        }

        /// <summary>
        /// 
        /// Creates a new read-only span over a portion of a target string
        /// using the range start and end indexes.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <param name="range">
        /// The range that has start and end indexes to use for slicing the string.
        /// </param>
        /// <returns>
        /// The read-only span representation of the string.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned span is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the span contents.
        /// 
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ReadOnlySpan<char> AsSpan(this PooledTextBuilder? text, Range range)
        {
            if (text is null)
            {
                Index startIndex = range.Start;
                Index endIndex = range.End;

                if (!startIndex.Equals(Index.Start) || !endIndex.Equals(Index.Start))
                {
                    ThrowHelper.ThrowArgumentNullException(ExceptionArgument.text);
                }

                return default;
            }

            (int start, int length) = range.GetOffsetAndLength(text.Length);

#if FEATURE_MEMORYMARSHAL_CREATEREADONLYSPAN && FEATURE_MEMORYMARSHAL_GETARRAYDATAREFERENCE
            // J2N: Careful - need to create a local copy because it could move.
            char[] chars = text.buffer.m_Chars;
            return MemoryMarshal.CreateReadOnlySpan<char>(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(chars),
                (nint)(uint)start /* force zero-extension */), length);
#else
            return new ReadOnlySpan<char>(text.buffer.m_Chars, start, length);
#endif
        }

#endif

        /// <summary>
        /// 
        /// Creates a new <see cref="ReadOnlyMemory{T}"/> over the portion of the target string.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <returns>
        /// The read-only character memory representation of the string, or <c>default</c> if
        /// <paramref name="text"/> is <c>null</c>.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned memory is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the memory contents.
        /// 
        /// </remarks>
        public static ReadOnlyMemory<char> AsMemory(this PooledTextBuilder? text)
        {
            if (text is null)
                return default;

            return new ReadOnlyMemory<char>(text.buffer.m_Chars, 0, text.Length);
        }

        /// <summary>
        /// 
        /// Creates a new <see cref="ReadOnlyMemory{T}"/> over the portion of the target string.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <param name="start">
        /// The index at which to begin this slice.
        /// </param>
        /// <returns>
        /// Returns default when <paramref name="text"/> is null.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned memory is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the memory contents.
        /// 
        /// </remarks>
        public static ReadOnlyMemory<char> AsMemory(this PooledTextBuilder? text, int start)
        {
            if (text == null)
            {
                if (start != 0)
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
                return default;
            }

            if ((uint)start > (uint)text.Length)
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);

            return new ReadOnlyMemory<char>(text.buffer.m_Chars, start, text.Length - start);
        }

        /// <summary>
        /// 
        /// Creates a new <see cref="ReadOnlyMemory{T}"/> over the portion of the target string.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <param name="start">
        /// The index at which to begin this slice.
        /// </param>
        /// <param name="length">
        /// The desired length for the slice (exclusive).
        /// </param>
        /// <returns>
        /// The read-only character memory representation of the string, or <c>default</c>
        /// if <paramref name="text"/> is <c>null</c>.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned memory is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the memory contents.
        /// 
        /// </remarks>
        public static ReadOnlyMemory<char> AsMemory(this PooledTextBuilder? text, int start, int length)
        {
            if (text == null)
            {
                if (start != 0 || length != 0)
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
                return default;
            }

            if (IntPtr.Size == 8) // 64-bit process
            {
                // See comment in Span<T>.Slice for how this works.
                if ((ulong)(uint)start + (ulong)(uint)length > (ulong)(uint)text.Length)
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
            }
            else
            {
                if ((uint)start > (uint)text.Length || (uint)length > (uint)(text.Length - start))
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
            }

            return new ReadOnlyMemory<char>(text.buffer.m_Chars, start, length);
        }

#if FEATURE_INDEX_RANGE
        /// <summary>
        /// 
        /// Creates a new <see cref="ReadOnlyMemory{T}"/> over the portion of the target string.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <param name="startIndex">
        /// The index at which to begin this slice.
        /// </param>
        /// <returns>
        /// The read-only character memory representation of the string.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned memory is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the memory contents.
        /// 
        /// </remarks>
        public static ReadOnlyMemory<char> AsMemory(this PooledTextBuilder? text, Index startIndex)
        {
            if (text == null)
            {
                if (!startIndex.Equals(Index.Start))
                    ThrowHelper.ThrowArgumentNullException(ExceptionArgument.text);

                return default;
            }

            int actualIndex = startIndex.GetOffset(text.Length);
            if ((uint)actualIndex > (uint)text.Length)
                ThrowHelper.ThrowArgumentOutOfRangeException();

            return new ReadOnlyMemory<char>(text.buffer.m_Chars, actualIndex, text.Length - actualIndex);
        }

        /// <summary>
        /// 
        /// Creates a new <see cref="ReadOnlyMemory{T}"/> over the portion of the target string.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target string.
        /// </param>
        /// <param name="range">
        /// The range used to indicate the start and length of the sliced string.
        /// </param>
        /// <returns>
        /// The read-only character memory representation of the string.
        /// </returns>
        /// <remarks>
        /// 
        /// Returns <see langword="default"/> when <paramref name="text"/> is <see langword="null"/>.
        /// <para/>
        /// The returned memory is only valid while the underlying <see cref="PooledTextBuilder"/> remains unchanged.
        /// Concurrent mutation invalidates the memory contents.
        /// 
        /// </remarks>
        public static ReadOnlyMemory<char> AsMemory(this PooledTextBuilder? text, Range range)
        {
            if (text == null)
            {
                Index startIndex = range.Start;
                Index endIndex = range.End;

                if (!startIndex.Equals(Index.Start) || !endIndex.Equals(Index.Start))
                    ThrowHelper.ThrowArgumentNullException(ExceptionArgument.text);

                return default;
            }

            (int start, int length) = range.GetOffsetAndLength(text.Length);
            return new ReadOnlyMemory<char>(text.buffer.m_Chars, start, length);
        }

#endif

        /// <summary>
        /// 
        /// Appends the string representation of a specified object to this instance using the specified format
        /// and culture-specific format information.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target builder.
        /// </param>
        /// <param name="value">
        /// The object to append.
        /// </param>
        /// <param name="format">
        /// A standard or custom format string.
        /// </param>
        /// <param name="provider">
        /// An object that supplies culture-specific formatting information.
        /// </param>
        /// <returns>
        /// A reference to this instance after the operation has completed.
        /// </returns>
        /// <remarks>
        /// 
        /// <paramref name="format"/> and <paramref name="provider"/> are only applied if the object implements <see cref="ISpanFormattable"/>,
        /// <see cref="IFormattable"/>, <c>IStructuralFormattable</c>, or subclasses <see cref="Number"/>.
        /// <para/>
        /// The capacity of this instance is adjusted as needed.
        /// <para/>
        /// <b>Notes to Callers</b>
        /// <para/>
        /// When you instantiate an <see cref="PooledTextBuilder"/> object by calling <see cref="PooledTextBuilder(int, int)"/>,
        /// both the length and the capacity of the <see cref="PooledTextBuilder"/> instance can grow beyond
        /// the value of its <see cref="PooledTextBuilder.MaxCapacity"/> property. This can occur particularly when you call the <see cref="PooledTextBuilder.Append(string)"/>
        /// and <see cref="PooledTextBuilder.AppendFormat(string, object?)"/> methods to append small strings.
        /// 
        /// </remarks>
        public static PooledTextBuilder Append(this PooledTextBuilder text, object? value, string? format = null, IFormatProvider? provider = null)
        {
            if (text is null)
                throw new ArgumentNullException(nameof(text));

            text.buffer.AppendInternal(value, format, provider);
            return text;
        }

        /// <summary>
        /// 
        /// Inserts the string representation of an object into this instance at the specified character position.
        /// 
        /// </summary>
        /// <param name="text">
        /// The target builder.
        /// </param>
        /// <param name="index">
        /// The position in this instance where insertion begins.
        /// </param>
        /// <param name="value">
        /// The object to insert, or <see langword="null"/>.
        /// </param>
        /// <param name="format">
        /// A standard or custom format string.
        /// </param>
        /// <param name="provider">
        /// An object that supplies culture-specific formatting information.
        /// </param>
        /// <returns>
        /// A reference to this instance after the append operation has completed.
        /// </returns>
        /// <remarks>
        /// 
        /// <paramref name="format"/> and <paramref name="provider"/> are only applied if the object implements <see cref="ISpanFormattable"/>,
        /// <see cref="IFormattable"/>, <c>IStructuralFormattable</c>, or subclasses <see cref="Number"/>.
        /// <para/>
        /// Existing characters are shifted to make room for the new text. The capacity of this instance is adjusted as needed.
        /// <para/>
        /// If <paramref name="value"/> is <see langword="null"/>, the <see cref="PooledTextBuilder"/> is not changed.
        /// 
        /// </remarks>
        public static PooledTextBuilder Insert(this PooledTextBuilder text, int index, object? value, string? format = null, IFormatProvider? provider = null)
        {
            if (text is null)
                throw new ArgumentNullException(nameof(text));

            text.buffer.InsertInternal(index, value, format, provider);
            return text;
        }

    }
}
