//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     Instead of editing this file, the MutableTextBuffer*.cs files should be edited
//     which will propagate the edits to this file.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using J2N.CodeGeneration;
using J2N.Numerics;
using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Collections.Generic;
using System.Globalization;
using J2N.Buffers;
using J2N.Collections;
using System.Buffers;
using System.Text;
using System.ComponentModel;
using J2N.Numerics.Formatters;
using J2N.Collections.Generic;

namespace J2N.Text
{

    public partial class SynchronizedTextBuilder
    {
        /// <summary>Gets or sets the maximum number of characters that can be contained in the memory allocated by the current instance.</summary>
        /// <value>
        /// The maximum number of characters that can be contained in the memory allocated by the current instance.
        /// Its value can range from <see cref="Length"/> to <see cref="SynchronizedTextBuilder.MaxCapacity"/>.
        /// </value>
        /// <exception cref="ArgumentOutOfRangeException">
        /// The value specified for a set operation is less than the current length of this instance.
        /// <para/>
        /// -or-
        /// <para/>
        /// The value specified for a set operation is greater than the maximum capacity.
        /// </exception>
        /// <remarks>
        /// <see cref="Capacity"/> does not affect the string value of the current instance. <see cref="Capacity"/> can
        /// be decreased as long as it is not less than <see cref="Length"/>.
        /// <para/>
        /// The <see cref="SynchronizedTextBuilder"/> dynamically allocates more space when required and increases
        /// <see cref="Capacity"/> accordingly. For performance reasons, a <see cref="SynchronizedTextBuilder"/> might
        /// allocate more memory than needed. The amount of memory allocated is implementation-specific.
        /// </remarks>
        public int Capacity
        {
            get
            {
                lock (syncRoot)
                {
                    return buffer.Capacity;
                }
            }
            set
            {
                lock (syncRoot)
                {
                    buffer.Capacity = value;
                }
            }
        }

        /// <summary>Gets the maximum capacity of this instance.</summary>
        /// <value>The maximum number of characters this instance can hold.</value>
        /// <remarks>
        /// The maximum capacity for this implementation is <c>Array.MaxLength</c> on .NET 6.0
        /// or higher. On earlier versions of .NET, the maximum capacity is <c>2_146_435_071</c>.
        /// You can explicitly set the maximum capacity of a <see cref="SynchronizedTextBuilder"/>
        /// object by calling <see cref="SynchronizedTextBuilder(int, int)"/>.
        /// <para/>
        /// <b>Notes to Callers</b>
        /// <para/>
        /// When you instantiate a <see cref="SynchronizedTextBuilder"/> object by calling <see cref="SynchronizedTextBuilder(int, int)"/>,
        /// both the length and the capacity of the <see cref="SynchronizedTextBuilder"/> instance can grow beyond
        /// the value of its <see cref="SynchronizedTextBuilder.MaxCapacity"/> property. This can occur particularly when you call the <see cref="SynchronizedTextBuilderExtensions.Append{TBuilder}(TBuilder, string?)"/>
        /// and <see cref="SynchronizedTextBuilderExtensions.AppendFormat{TBuilder}(TBuilder, string, object?)"/> methods to append small strings.
        /// </remarks>
        public int MaxCapacity
        {
            get
            {
                lock (syncRoot)
                {
                    return buffer.MaxCapacity;
                }
            }
        }

        /// <summary>Gets or sets the length of the current <see cref="SynchronizedTextBuilder"/> object.</summary>
        /// <value>The length of this instance.</value>
        /// <exception cref="ArgumentOutOfRangeException">
        /// The value specified for a set operation
        /// is less than zero or greater than <see cref="MaxCapacity"/>.
        /// </exception>
        /// <remarks>
        /// The length of a <see cref="SynchronizedTextBuilder"/> object is defined by its number of
        /// <see cref="char"/> objects.
        /// <para/>
        /// Like the <see cref="string.Length"/> property, the <see cref="Length"/> property indicates
        /// the length of the current string object. Unlike the <see cref="string.Length"/> property,
        /// which is read-only, the <see cref="Length"/> property allows you to modify the length of
        /// the string stored to the <see cref="SynchronizedTextBuilder"/> object.
        /// <para/>
        /// If the specified length is less than the current length, the current <see cref="SynchronizedTextBuilder"/>
        /// object is truncated to the specified length. If the specified length is greater than the current
        /// length, the end of the string value of the current <see cref="SynchronizedTextBuilder"/> object is padded
        /// with the Unicode NULL character (U+0000).
        /// <para/>
        /// If the specified length is greater than the current capacity, <see cref="Capacity"/> increases so
        /// that it is greater than or equal to the specified length.
        /// </remarks>
        public int Length
        {
            get
            {
                lock (syncRoot)
                {
                    return buffer.Length;
                }
            }
            set
            {
                lock (syncRoot)
                {
                    buffer.Length = value;
                }
            }
        }

        /// <summary>Gets or sets the character at the specified character position in this instance.</summary>
        /// <param name="index">The position of the character.</param>
        /// <value>The Unicode character at position <paramref name="index"/>.</value>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="index"/> is outside
        /// the bounds of this instance while setting a character.
        /// </exception>
        /// <exception cref="IndexOutOfRangeException">
        /// <paramref name="index"/> is outside the bounds
        /// of this instance while getting a character.
        /// </exception>
        /// <remarks>
        /// The index parameter is the position of a character within the <see cref="SynchronizedTextBuilder"/>.
        /// The first character in the string is at index 0. The length of a string is the number of
        /// characters it contains. The last accessible character of a <see cref="SynchronizedTextBuilder"/> instance
        /// is at index Length - 1.
        /// <para/>
        /// <see cref="this[int]"/> is the default property of the <see cref="SynchronizedTextBuilder"/>  class.
        /// In C#, it is an indexer. This means that individual characters can be retrieved from the <see cref="this[int]"/>
        /// property as shown in the following example, which counts the number of alphabetic, white-space, and punctuation
        /// characters in a string.
        /// <code>
        /// using System;
        /// using System.Text;
        /// 
        /// public class Example
        /// {
        ///     public static void Main()
        ///     {
        ///         int nAlphabeticChars = 0;
        ///         int nWhitespace = 0;
        ///         int nPunctuation = 0;
        ///         SynchronizedTextBuilder sb = new SynchronizedTextBuilder("This is a simple sentence.");
        /// 
        ///         for (int ctr = 0; ctr &lt; sb.Length; ctr++)
        ///         {
        ///             char ch = sb[ctr];
        ///             if (char.IsLetter(ch)) { nAlphabeticChars++; continue; }
        ///             if (char.IsWhiteSpace(ch)) { nWhitespace++; continue; }
        ///             if (char.IsPunctuation(ch)) nPunctuation++;
        ///         }
        /// 
        ///         Console.WriteLine("The sentence '{0}' has:", sb);
        ///         Console.WriteLine("   Alphabetic characters: {0}", nAlphabeticChars);
        ///         Console.WriteLine("   White-space characters: {0}", nWhitespace);
        ///         Console.WriteLine("   Punctuation characters: {0}", nPunctuation);
        ///     }
        /// }
        /// // The example displays the following output:
        /// //       The sentence 'This is a simple sentence.' has:
        /// //          Alphabetic characters: 21
        /// //          White-space characters: 4
        /// //          Punctuation characters: 1
        /// </code>
        /// <para/>
        /// Unlike the <see cref="StringBuilder"/> class, <see cref="SynchronizedTextBuilder"/>'s indexer does
        /// not suffer from degraded performance due to chunky memory, since <see cref="SynchronizedTextBuilder"/>
        /// uses a single contiguous block of characters in memory.
        /// </remarks>
        [IndexerName("Chars")]
        public char this[int index]
        {
            get
            {
                lock (syncRoot)
                {
                    return buffer[index];
                }
            }
            set
            {
                lock (syncRoot)
                {
                    buffer[index] = value;
                }
            }
        }

        /// <summary>
        /// Returns a <see cref="Span{Char}"/> to write to that is at least the requested size
        /// (specified by <paramref name="sizeHint"/>).
        /// </summary>
        /// <param name="sizeHint">
        /// The minimum length of the returned <see cref="Span{Char}"/>.
        /// If 0, a non-empty buffer is returned.
        /// </param>
        /// <returns>
        /// A <see cref="Span{Char}"/> of at least the size <paramref name="sizeHint"/>.
        /// If <paramref name="sizeHint"/> is 0, returns a non-empty buffer.
        /// </returns>
        /// <exception cref="ArgumentOutOfRangeException"><paramref name="sizeHint"/> is less than zero.</exception>
        /// <remarks>
        /// This method never returns <see cref="Span{Char}.Empty"/>.
        /// <para/>
        /// The returned span provides direct access to the underlying memory of the <see cref="SynchronizedTextBuilder"/>.
        /// Callers must synchronize externally using <see cref="SynchronizedTextBuilder.SyncRoot"/> for the duration of the
        /// span usage if concurrent mutation is possible.
        /// </remarks>
        public Span<char> GetSpan(int sizeHint = 0)
        {
            return buffer.GetSpan(sizeHint);
        }

        /// <summary>
        /// Returns a <see cref="Memory{Char}"/> to write to that is at least the length
        /// specified by <paramref name="sizeHint"/>.
        /// </summary>
        /// <param name="sizeHint">
        /// The minimum requested length of the <see cref="Memory{Char}"/>.
        /// If 0, a non-empty buffer is returned.
        /// </param>
        /// <returns>
        /// A <see cref="Memory{Char}"/> whose length is at least <paramref name="sizeHint"/>.
        /// If <paramref name="sizeHint"/> is not provided or is equal to 0, some non-empty buffer is returned.
        /// </returns>
        /// <exception cref="ArgumentOutOfRangeException"><paramref name="sizeHint"/> is less than zero.</exception>
        /// <remarks>
        /// This method never returns <see cref="Memory{Char}.Empty"/>.
        /// <para/>
        /// The returned memory provides direct access to the underlying memory of the <see cref="SynchronizedTextBuilder"/>.
        /// Callers must synchronize externally using <see cref="SynchronizedTextBuilder.SyncRoot"/> for the duration of the
        /// span usage if concurrent mutation is possible.
        /// </remarks>
        public Memory<char> GetMemory(int sizeHint = 0)
        {
            return buffer.GetMemory(sizeHint);
        }

        /// <summary>
        /// Notifies the <see cref="SynchronizedTextBuilder"/> that <paramref name="count"/> items were
        /// written to the output <see cref="Span{Char}"/> or <see cref="Memory{Char}"/>.
        /// </summary>
        /// <param name="count">The number of items written.</param>
        /// <exception cref="ArgumentOutOfRangeException"><paramref name="count"/> is less than zero.</exception>
        /// <exception cref="InvalidOperationException">
        /// The method call attempts to advance past the remaining <see cref="Capacity"/>
        /// beyond <see cref="Length"/>.
        /// </exception>
        /// <remarks>
        /// You must request a new buffer after calling <see cref="Advance(int)"/> to continue writing more data
        /// and cannot write to a previously acquired buffer.
        /// <para/>
        /// This method is intended to be used in conjunction with either <see cref="GetSpan(int)"/> or <see cref="GetMemory(int)"/>.
        /// If concurrent mutation is possible, this method should be synchronized externally by the caller with either of those two
        /// methods using <see cref="SynchronizedTextBuilder.SyncRoot"/> for the duration of the memory usage.
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Advance(int count)
        {
            buffer.Advance(count);
        }

        /// <summary>
        /// Retrieves a sub-sequence from this instance.
        /// The sub-sequence starts at a specified character position and has a specified length.
        /// <para/>
        /// IMPORTANT: This method has .NET semantics, that is, the second parameter is a length,
        /// not an exclusive end index as it would be in Java.
        /// </summary>
        /// <param name="startIndex">
        /// The start index of the sub-sequence. It is inclusive, that
        /// is, the index of the first character that is included in the
        /// sub-sequence.
        /// </param>
        /// <param name="length">The number of characters to return in the sub-sequence.</param>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="startIndex"/> plus <paramref name="length"/> indicates a position not within this instance.
        /// <para/>
        /// -or-
        /// <para/>
        /// <paramref name="startIndex"/> or <paramref name="length"/> is less than zero.
        /// </exception>
        public ICharSequence Subsequence(int startIndex, int length)
        {
            lock (syncRoot)
            {
                return buffer.Subsequence(startIndex, length);
            }
        }

        /// <summary>
        /// Returns the code point at <paramref name="index"/> in the specified sequence of
        /// character units. If the unit at <paramref name="index"/> is a high-surrogate unit,
        /// <c><paramref name="index"/> + 1</c> is less than the length of the sequence and the unit at
        /// <c><paramref name="index"/> + 1</c> is a low-surrogate unit, then the supplementary code
        /// point represented by the pair is returned; otherwise the <see cref="char"/>
        /// value at <paramref name="index"/> is returned.
        /// </summary>
        /// <param name="index">
        /// The position in this <see cref="SynchronizedTextBuilder"/> from which to retrieve the code
        /// point.
        /// </param>
        /// <returns>
        /// The Unicode code point or <see cref="char"/> value at <paramref name="index"/> in
        /// this <see cref="SynchronizedTextBuilder"/>.
        /// </returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="index"/> is greater than or equal to <see cref="Length"/>.
        /// <para/>
        /// -or-
        /// <para/>
        /// <paramref name="index"/> is less than zero.
        /// </exception>
        public int CodePointAt(int index)
        {
            lock (syncRoot)
            {
                return buffer.CodePointAt(index);
            }
        }

        /// <summary>
        /// Returns the code point that precedes <paramref name="index"/> in the specified
        /// sequence of character units. If the unit at <c><paramref name="index"/> - 1</c> is a
        /// low-surrogate unit, <c><paramref name="index"/> - 2</c> is not negative and the unit at
        /// <c><paramref name="index"/> - 2</c> is a high-surrogate unit, then the supplementary code
        /// point represented by the pair is returned; otherwise the <see cref="char"/>
        /// value at <c><paramref name="index"/> - 1</c> is returned.
        /// </summary>
        /// <param name="index">
        /// The position in this <see cref="SynchronizedTextBuilder"/> following the code
        /// point that should be returned.
        /// </param>
        /// <returns>
        /// The Unicode code point or <see cref="char"/> value before <paramref name="index"/>
        /// in this <see cref="SynchronizedTextBuilder"/>.
        /// </returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// If the <paramref name="index"/> is less than
        /// 1 or greater than <see cref="Length"/>.
        /// </exception>
        public int CodePointBefore(int index)
        {
            lock (syncRoot)
            {
                return buffer.CodePointBefore(index);
            }
        }

        /// <summary>
        /// Returns the number of Unicode code points in the text range of the specified char sequence.
        /// The text range begins at the specified <paramref name="startIndex"/> and extends for the number
        /// of characters specified in <paramref name="length"/>.
        /// Unpaired surrogates within the text range count as one code point each.
        /// <para/>
        /// IMPORTANT: This method has .NET semantics. That is, the <paramref name="length"/> parameter
        /// is a length rather than an exclusive end index. To convert from
        /// Java, use <c>endIndex - startIndex</c> to obtain the length.
        /// </summary>
        /// <param name="startIndex">The index to the first char of the text range.</param>
        /// <param name="length">The number of characters to consider in this <see cref="SynchronizedTextBuilder"/>.</param>
        /// <returns>The number of Unicode code points in the specified text range.</returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="startIndex"/> plus <paramref name="length"/> indicates a position not within
        /// this <see cref="SynchronizedTextBuilder"/>.
        /// <para/>
        /// -or-
        /// <para/>
        /// <paramref name="startIndex"/> or <paramref name="length"/> is less than zero.
        /// </exception>
        public int CodePointCount(int startIndex, int length)
        {
            lock (syncRoot)
            {
                return buffer.CodePointCount(startIndex, length);
            }
        }

        /// <summary>
        /// Returns the index within the given char sequence that is offset from the given <paramref name="index"/> by
        /// <paramref name="codePointOffset"/> code points. Unpaired surrogates within the text range given by
        /// <paramref name="index"/> and <paramref name="codePointOffset"/> count as one code point each.
        /// </summary>
        /// <param name="index">The index to be offset.</param>
        /// <param name="codePointOffset">
        /// The number of code points to look backwards or forwards; may
        /// be a negative or positive value.
        /// </param>
        /// <returns>The index within the char sequence, offset by <paramref name="codePointOffset"/> code points.</returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="index"/> is less than zero or greater than <see cref="Length"/>.
        /// <para/>
        /// -or-
        /// <para/>
        /// <paramref name="codePointOffset"/> is positive and the subsequence starting with
        /// <paramref name="index"/> has fewer than <paramref name="codePointOffset"/> code points.
        /// <para/>
        /// -or-
        /// <para/>
        /// <paramref name="codePointOffset"/> is negative and the subsequence before <paramref name="index"/>
        /// has fewer than the absolute value of <paramref name="codePointOffset"/> code points.
        /// </exception>
        public int OffsetByCodePoints(int index, int codePointOffset)
        {
            lock (syncRoot)
            {
                return buffer.OffsetByCodePoints(index, codePointOffset);
            }
        }

        /// <summary>Ensures that the capacity of this builder is at least the specified value.</summary>
        /// <param name="capacity">The minimum capacity to ensure.</param>
        /// <returns>The new capacity of this instance.</returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="capacity"/> is less than zero.
        /// <para/>
        /// -or-
        /// <para/>
        /// Enlarging the value of this instance would exceed <see cref="MaxCapacity"/>.
        /// </exception>
        /// <remarks>
        /// If the current capacity is less than the <paramref name="capacity"/> parameter,
        /// memory for this instance is reallocated to hold at least <paramref name="capacity"/> number
        /// of characters; otherwise, no memory is changed.
        /// </remarks>
        public int EnsureCapacity(int capacity)
        {
            lock (syncRoot)
            {
                return buffer.EnsureCapacity(capacity);
            }
        }

        /// <summary>
        /// Sets the capacity of a <see cref="SynchronizedTextBuilder"/> object to the actual number of characters
        /// it contains.
        /// </summary>
        /// <remarks>
        /// This method is similar to <c>trimToSize()</c> in the JDK.
        /// <para/>
        /// You can use the <see cref="TrimExcess()"/> method to minimize a <see cref="SynchronizedTextBuilder"/> object's
        /// memory overhead once it is known that no new characters will be added. To completely clear an
        /// <see cref="SynchronizedTextBuilder"/> object and release all memory referenced by it, call this method
        /// after calling the <see cref="SynchronizedTextBuilderExtensions.Clear{TBuilder}(TBuilder)"/> method or setting <see cref="Length"/> property to 0.
        /// <para/>
        /// If the capacity is already equal to the current length, this method has no effect.
        /// </remarks>
        public void TrimExcess()
        {
            lock (syncRoot)
            {
                buffer.TrimExcess();
            }
        }

        /// <summary>
        /// Copies the characters from a specified segment of this instance to a specified segment of a destination
        /// <see cref="char"/> array.
        /// </summary>
        /// <param name="sourceIndex">
        /// The starting position in this instance where characters will be copied from.
        /// The index is zero-based.
        /// </param>
        /// <param name="destination">The array where characters will be copied.</param>
        /// <param name="destinationIndex">
        /// The starting position in <paramref name="destination"/> where characters will be copied.
        /// The index is zero-based.
        /// </param>
        /// <param name="count">The number of characters to be copied.</param>
        /// <exception cref="ArgumentNullException"><paramref name="destination"/> is <see langword="null"/>.</exception>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="sourceIndex"/>, <paramref name="destinationIndex"/>, or <paramref name="count"/>, is less than zero.
        /// <para/>
        /// -or-
        /// <para/>
        /// <paramref name="sourceIndex"/> is greater than the length of this instance.
        /// </exception>
        /// <exception cref="ArgumentException">
        /// <paramref name="sourceIndex"/> + <paramref name="count"/> is greater than the length of this instance.
        /// <para/>
        /// -or-
        /// <para/>
        /// <paramref name="destinationIndex"/> + <paramref name="count"/> is greater than the length of <paramref name="destination"/>.
        /// </exception>
        /// <remarks>
        /// The <see cref="CopyTo(int, char[], int, int)"/> method is intended to be used in the rare situation when you need to
        /// efficiently copy successive sections of a <see cref="SynchronizedTextBuilder"/> object to an array. The array should be a
        /// fixed size, preallocated, reusable, and possibly globally accessible.
        /// <para/>
        /// To access the characters for processing without allocating any heap memory, better alternatives are to use
        /// <see cref="this[int]"/>, <see cref="SynchronizedTextBuilderExtensions.AsSpan(SynchronizedTextBuilder?, int, int)"/> or <see cref="CopyTo(int, Span{char}, int)"/>.
        /// </remarks>
        public void CopyTo(int sourceIndex, char[] destination, int destinationIndex, int count)
        {
            lock (syncRoot)
            {
                buffer.CopyTo(sourceIndex, destination, destinationIndex, count);
            }
        }

        /// <summary>Copies the characters from a specified segment of this instance to a destination <see cref="char"/> span.</summary>
        /// <param name="sourceIndex">
        /// The starting position in this instance where characters will be copied from.
        /// The index is zero-based.
        /// </param>
        /// <param name="destination">The writable span where characters will be copied.</param>
        /// <param name="count">The number of characters to be copied.</param>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="sourceIndex"/> or <paramref name="count"/> is less than 0.
        /// <para/>
        /// -or-
        /// <para/>
        /// <paramref name="sourceIndex"/> is greater than <see cref="Length"/>.
        /// </exception>
        /// <exception cref="ArgumentException"><paramref name="sourceIndex"/> + <paramref name="count"/> is greater than <see cref="Length"/>.</exception>
        /// <remarks>
        /// The <see cref="CopyTo(int, Span{char}, int)"/> method is intended to be used in the rare situation
        /// when you need to efficiently copy successive sections of a <see cref="SynchronizedTextBuilder"/> object to a span.
        /// <para/>
        /// To access the characters for processing without alocating any heap memory, better alternatives are to use
        /// <see cref="this[int]"/> or <see cref="SynchronizedTextBuilderExtensions.AsSpan(SynchronizedTextBuilder?, int, int)"/>.
        /// </remarks>
        public void CopyTo(int sourceIndex, Span<char> destination, int count)
        {
            lock (syncRoot)
            {
                buffer.CopyTo(sourceIndex, destination, count);
            }
        }

        /// <summary>Returns a value indicating whether this instance is equal to a specified object.</summary>
        /// <param name="sb">An object to compare with this instance, or <see langword="null"/>.</param>
        /// <returns>
        /// <see langword="true"/> if the characters in this instance and <paramref name="sb"/> are the same;
        /// otherwise, <see langword="false"/>.
        /// </returns>
        /// <remarks>
        /// The current instance and <paramref name="sb"/> are equal if the strings assigned to both
        /// <see cref="SynchronizedTextBuilder"/> objects are the same. To determine equality, the
        /// <see cref="Equals(SynchronizedTextBuilder)"/> method uses ordinal comparison.
        /// </remarks>
        public bool Equals(SynchronizedTextBuilder? sb)
        {
            lock (syncRoot)
            {
                return buffer.Equals(sb?.buffer);
            }
        }

        /// <summary>Returns a value indicating whether this instance is equal to a specified object.</summary>
        /// <param name="sb">An object to compare with this instance, or <see langword="null"/>.</param>
        /// <returns>
        /// <see langword="true"/> if the characters in this instance and <paramref name="sb"/> are the same;
        /// otherwise, <see langword="false"/>.
        /// </returns>
        /// <remarks>
        /// The current instance and <paramref name="sb"/> are equal if the strings assigned to both
        /// objects are the same. To determine equality, the <see cref="Equals(SynchronizedTextBuilder)"/>
        /// method uses ordinal comparison.
        /// </remarks>
        /// <remarks>
        /// The <see cref="Equals(StringBuilder)"/> method performs an ordinal comparison to determine
        /// whether the characters in the current instance and span are equal.
        /// </remarks>
        public bool Equals(StringBuilder? sb)
        {
            lock (syncRoot)
            {
                return buffer.Equals(sb);
            }
        }

        /// <summary>
        /// Returns a value indicating whether the characters in this instance are equal to the
        /// characters in a specified read-only character span.
        /// </summary>
        /// <param name="span">The character span to compare with the current instance.</param>
        /// <returns>
        /// <see langword="true"/> if the characters in this instance and <paramref name="span"/> are the same;
        /// otherwise, <see langword="false"/>.
        /// </returns>
        /// <remarks>
        /// The <see cref="Equals(SynchronizedTextBuilder)"/> method performs an ordinal comparison to determine
        /// whether the characters in the current instance and span are equal.
        /// </remarks>
        public bool Equals(ReadOnlySpan<char> span)
        {
            lock (syncRoot)
            {
                return buffer.Equals(span);
            }
        }

        /// <summary>Converts the value of this instance to a <see cref="string"/>.</summary>
        /// <returns>A string whose value is the same as this instance.</returns>
        /// <remarks>
        /// This method causes a heap allocation. As an allocation-free alternative,
        /// you may call the <see cref="SynchronizedTextBuilderExtensions.AsSpan(SynchronizedTextBuilder?)"/> method
        /// to get a <see cref="ReadOnlySpan{T}"/> representing the characters of this
        /// <see cref="SynchronizedTextBuilder"/> instance.
        /// <para/>
        /// Call the <see cref="ToString()"/> method to convert the
        /// <see cref="SynchronizedTextBuilder"/> object to a <see cref="string"/> object before
        /// you can pass the string represented by the <see cref="SynchronizedTextBuilder"/> object to
        /// a method that has a <see cref="string"/> parameter or display it in the user interface.
        /// </remarks>
        public override string ToString()
        {
            lock (syncRoot)
            {
                return buffer.ToString();
            }
        }

        /// <summary>Converts the value of a substring of this instance to a <see cref="string"/>.</summary>
        /// <param name="startIndex">The starting position of the substring in this instance.</param>
        /// <returns>
        /// A string whose value is the same as the specified substring of this instance.
        /// That is, from <paramref name="startIndex"/> to the end of the string.
        /// </returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="startIndex"/> is less than 0 or greater than
        /// <see cref="Length"/>.
        /// </exception>
        /// <remarks>
        /// This method causes a heap allocation. As an allocation-free alternative,
        /// you may call the <see cref="SynchronizedTextBuilderExtensions.AsSpan(SynchronizedTextBuilder?, int)"/> method
        /// to get a <see cref="ReadOnlySpan{T}"/> representing the characters of the substring of this
        /// <see cref="SynchronizedTextBuilder"/> instance.
        /// <para/>
        /// Call the <see cref="ToString(int)"/> method to convert the
        /// <see cref="SynchronizedTextBuilder"/> object to a <see cref="string"/> object before
        /// you can pass the string represented by the <see cref="SynchronizedTextBuilder"/> object to
        /// a method that has a <see cref="string"/> parameter or display it in the user interface.
        /// </remarks>
        public string ToString(int startIndex)
        {
            lock (syncRoot)
            {
                return buffer.ToString(startIndex);
            }
        }

        /// <summary>Converts the value of a substring of this instance to a <see cref="string"/>.</summary>
        /// <param name="startIndex">The starting position of the substring in this instance.</param>
        /// <param name="length">The length of the substring.</param>
        /// <returns>A string whose value is the same as the specified substring of this instance.</returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="startIndex"/> or <paramref name="length"/> is less than zero.
        /// <para/>
        /// -or-
        /// <para/>
        /// The sum of <paramref name="startIndex"/> and <paramref name="length"/> is greater than the length
        /// of the current instance.
        /// </exception>
        /// <remarks>
        /// This method causes a heap allocation. As an allocation-free alternative,
        /// you may call the <see cref="SynchronizedTextBuilderExtensions.AsSpan(SynchronizedTextBuilder?, int, int)"/> method
        /// to get a <see cref="ReadOnlySpan{T}"/> representing the characters of the substring of this
        /// <see cref="SynchronizedTextBuilder"/> instance.
        /// <para/>
        /// Call the <see cref="ToString(int)"/> method to convert the
        /// <see cref="SynchronizedTextBuilder"/> object to a <see cref="string"/> object before
        /// you can pass the string represented by the <see cref="SynchronizedTextBuilder"/> object to
        /// a method that has a <see cref="string"/> parameter or display it in the user interface.
        /// </remarks>
        public string ToString(int startIndex, int length)
        {
            lock (syncRoot)
            {
                return buffer.ToString(startIndex, length);
            }
        }

        /// <summary>
        /// Appends and returns a writable <see cref="Span{Char}"/> of the specified length to this builder.
        /// Writes to the returned span will update the value of this instance.
        /// </summary>
        /// <param name="length">The number of characters to append to this instance.</param>
        /// <returns>
        /// >A <see cref="Span{Char}"/> wrapping a block of memory that is appended to the existing
        /// sequence of characters. The span may be written to by the caller to update this instance.
        /// </returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// <paramref name="length"/> is less than zero.
        /// <para/>
        /// -or-
        /// <para/>
        /// <paramref name="length"/> plus the current length of this instance exceeds <see cref="MaxCapacity"/>.
        /// </exception>
        /// <remarks>
        /// This method allows callers to append a block of a specific length to this instance that can be written
        /// to after the fact. This is most useful for passing a span to an API that writes directly into a character buffer,
        /// which can save a copy operation if the data fits in the returned span.
        /// <para/>
        /// The capacity is adjusted as needed.
        /// <para/>
        /// <b>Notes to Callers</b>
        /// <para/>
        /// When you instantiate a <see cref="SynchronizedTextBuilder"/> object by calling <see cref="SynchronizedTextBuilder(int, int)"/>,
        /// both the length and the capacity of the <see cref="SynchronizedTextBuilder"/> instance can grow beyond
        /// the value of its <see cref="MaxCapacity"/> property. This can occur particularly when you call the <see cref="SynchronizedTextBuilderExtensions.Append{TBuilder}(TBuilder, string?)"/>
        /// and <see cref="SynchronizedTextBuilderExtensions.AppendFormat{TBuilder}(TBuilder, string, object?)"/> methods to append small strings.
        /// <para/>
        /// The returned span provides direct access to the underlying memory of the <see cref="SynchronizedTextBuilder"/>.
        /// Callers must synchronize externally using <see cref="SynchronizedTextBuilder.SyncRoot"/> for the duration of the
        /// span usage if concurrent mutation is possible.
        /// </remarks>
        public Span<char> AppendSpan(int length)
        {
            return buffer.AppendSpan(length);
        }

        /// <summary>
        /// Reports the zero-based index of the first occurrence of the specified Unicode character
        /// in this instance.
        /// </summary>
        /// <param name="value">A Unicode character to seek.</param>
        /// <returns>
        /// The zero-based index position of <paramref name="value"/> if that character
        /// is found, or -1 if it is not.
        /// </returns>
        /// <remarks>
        /// Index numbering starts from zero.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is considered
        /// equivalent to another character only if their Unicode scalar values are the same.
        /// </remarks>
        public int IndexOf(char value)
        {
            lock (syncRoot)
            {
                return buffer.IndexOf(value);
            }
        }

        /// <summary>Reports the zero-based index of the first occurrence of the specified string.</summary>
        /// <param name="value">The string to find.</param>
        /// <returns>
        /// The zero-based index position of <paramref name="value"/> from the start of
        /// the current instance if that sequence of characters is found, or -1 if it is not.
        /// If <paramref name="value"/> is <see cref="string.Empty"/>, the return value
        /// is 0.
        /// </returns>
        /// <exception cref="ArgumentNullException"><paramref name="value"/> is <see langword="null"/>.</exception>
        /// <remarks>
        /// Index numbering starts from zero.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is considered
        /// equivalent to another character only if their Unicode scalar values are the same.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty string, which will
        /// always return 0.
        /// </remarks>
        public int IndexOf(string value)
        {
            lock (syncRoot)
            {
                return buffer.IndexOf(value);
            }
        }

        /// <summary>Reports the zero-based index of the first occurrence of the specified span.</summary>
        /// <param name="value">The span to find.</param>
        /// <returns>
        /// The zero-based index position of <paramref name="value"/> from the start of
        /// the current instance if that sequence of characters is found, or -1 if it is not.
        /// If <paramref name="value"/> is <see cref="ReadOnlySpan{T}.Empty"/>, the return value
        /// is 0.
        /// </returns>
        /// <remarks>
        /// Index numbering starts from zero.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is considered
        /// equivalent to another character only if their Unicode scalar values are the same.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty span, which will
        /// always return 0.
        /// </remarks>
        public int IndexOf(ReadOnlySpan<char> value)
        {
            lock (syncRoot)
            {
                return buffer.IndexOf(value);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the first occurrence of the specified string beginning
        /// at the specified index in this instance.
        /// </summary>
        /// <param name="value">The string to find.</param>
        /// <param name="startIndex">The search starting position.</param>
        /// <returns>
        /// The zero-based index position of <paramref name="value"/> from the specified index of
        /// the current instance if that sequence of characters is found, or -1 if it is not.
        /// If <paramref name="value"/> is empty, the return value is the effective start index
        /// after clamping.
        /// </returns>
        /// <exception cref="ArgumentNullException"><paramref name="value"/> is <see langword="null"/>.</exception>
        /// <remarks>
        /// Index numbering starts from zero. The <paramref name="startIndex"/> parameter is clamped to
        /// the valid range of the current instance. Values less than zero are treated as zero, and values
        /// greater than <see cref="Length" /> are treated as equal to <see cref="Length" />.
        /// If <paramref name="startIndex"/> equals <see cref="Length" />, this method
        /// returns -1 for non-empty searches. If <paramref name="value"/> is empty, this method returns
        /// the effective start index after clamping. The search is case-sensitive.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is considered
        /// equivalent to another character only if their Unicode scalar values are the same.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty string, which will
        /// always return <paramref name="startIndex"/>.
        /// <para/>
        /// If <paramref name="startIndex"/> is less than zero, it is treated as zero. If it is greater
        /// than <see cref="Length"/>, it is treated as equal to <see cref="Length"/>.
        /// </remarks>
        public int IndexOf(string value, int startIndex)
        {
            lock (syncRoot)
            {
                return buffer.IndexOf(value, startIndex);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the first occurrence of the specified span beginning
        /// at the specified index in this instance.
        /// </summary>
        /// <param name="value">The span to find.</param>
        /// <param name="startIndex">The search starting position.</param>
        /// <returns>
        /// The zero-based index position of <paramref name="value"/> from the start of
        /// the current instance if that sequence of characters is found, or -1 if it is not.
        /// If <paramref name="value"/> is empty, the return value is the effective start index
        /// after clamping.
        /// </returns>
        /// <remarks>
        /// Index numbering starts from zero. The <paramref name="startIndex"/> parameter is clamped to
        /// the valid range of the current instance. Values less than zero are treated as zero, and values
        /// greater than <see cref="Length" /> are treated as equal to <see cref="Length" />.
        /// If <paramref name="startIndex"/> equals <see cref="Length" />, this method
        /// returns -1 for non-empty searches. If <paramref name="value"/> is empty, this method returns
        /// the effective start index after clamping. The search is case-sensitive.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is considered
        /// equivalent to another character only if their Unicode scalar values are the same.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty span, which will
        /// always return <paramref name="startIndex"/>.
        /// <para/>
        /// If <paramref name="startIndex"/> is less than zero, it is treated as zero. If it is greater
        /// than <see cref="Length"/>, it is treated as equal to <see cref="Length"/>.
        /// </remarks>
        public int IndexOf(ReadOnlySpan<char> value, int startIndex)
        {
            lock (syncRoot)
            {
                return buffer.IndexOf(value, startIndex);
            }
        }

        /// <summary>Reports the zero-based index of the first occurrence of the specified string.</summary>
        /// <param name="value">The string to find.</param>
        /// <param name="comparisonType">
        /// One of the enumeration values that determines how the current instance
        /// and <paramref name="value"/> are compared.
        /// </param>
        /// <returns>
        /// The zero-based index position of <paramref name="value"/> from the start of
        /// the current instance if that sequence of characters is found, or -1 if it is not.
        /// If <paramref name="value"/> is <see cref="string.Empty"/>, the return value
        /// is 0.
        /// </returns>
        /// <exception cref="ArgumentNullException"><paramref name="value"/> is <see langword="null"/>.</exception>
        /// <remarks>
        /// Index numbering starts from zero.
        /// <para/>
        /// The <paramref name="comparisonType"/> parameter specifies to search for the <paramref name="value"/>
        /// parameter using the current or invariant culture, using a case-sensitive or case-insensitive search,
        /// and using word or ordinal comparison rules.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty string, which will
        /// always return 0.
        /// <para/>
        /// On older platforms than .NET Core, this overload provides optimizations for
        /// <see cref="StringComparison.OrdinalIgnoreCase"/> over and above the System.Memory package.
        /// </remarks>
        public int IndexOf(string value, StringComparison comparisonType)
        {
            lock (syncRoot)
            {
                return buffer.IndexOf(value, comparisonType);
            }
        }

        /// <summary>Reports the zero-based index of the first occurrence of the specified span.</summary>
        /// <param name="value">The span to find.</param>
        /// <param name="comparisonType">
        /// One of the enumeration values that determines how the current instance
        /// and <paramref name="value"/> are compared.
        /// </param>
        /// <returns>
        /// The zero-based index position of <paramref name="value"/> from the start of
        /// the current instance if that sequence of characters is found, or -1 if it is not.
        /// If <paramref name="value"/> is <see cref="ReadOnlySpan{T}.Empty"/>, the return value
        /// is 0.
        /// </returns>
        /// <exception cref="ArgumentNullException"><paramref name="value"/> is <see langword="null"/>.</exception>
        /// <remarks>
        /// Index numbering starts from zero.
        /// <para/>
        /// The <paramref name="comparisonType"/> parameter specifies to search for the <paramref name="value"/>
        /// parameter using the current or invariant culture, using a case-sensitive or case-insensitive search,
        /// and using word or ordinal comparison rules.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty span, which will
        /// always return 0.
        /// <para/>
        /// On older platforms than .NET Core, this overload provides optimizations for
        /// <see cref="StringComparison.OrdinalIgnoreCase"/> over and above the System.Memory package.
        /// </remarks>
        public int IndexOf(ReadOnlySpan<char> value, StringComparison comparisonType)
        {
            lock (syncRoot)
            {
                return buffer.IndexOf(value, comparisonType);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the first occurrence of the specified string beginning
        /// at the specified index in this instance.
        /// </summary>
        /// <param name="value">The string to find.</param>
        /// <param name="startIndex">The search starting position.</param>
        /// <param name="comparisonType">
        /// One of the enumeration values that determines how the current instance
        /// and <paramref name="value"/> are compared.
        /// </param>
        /// <returns>
        /// The zero-based index position of <paramref name="value"/> from the start of
        /// the current instance if that sequence of characters is found, or -1 if it is not.
        /// If <paramref name="value"/> is empty, the return value is the effective start index
        /// after clamping.
        /// </returns>
        /// <exception cref="ArgumentNullException"><paramref name="value"/> is <see langword="null"/>.</exception>
        /// <exception cref="ArgumentException">
        /// <paramref name="comparisonType"/> is not a
        /// <see cref="StringComparison"/> value.
        /// </exception>
        /// <remarks>
        /// Index numbering starts from zero. The <paramref name="startIndex"/> parameter is clamped to
        /// the valid range of the current instance. Values less than zero are treated as zero, and values
        /// greater than <see cref="Length" /> are treated as equal to <see cref="Length" />.
        /// If <paramref name="startIndex"/> equals <see cref="Length" />, this method
        /// returns -1 for non-empty searches. If <paramref name="value"/> is empty, this method returns
        /// the effective start index after clamping.
        /// <para/>
        /// The <paramref name="comparisonType"/> parameter specifies to search for the <paramref name="value"/>
        /// parameter using the current or invariant culture, using a case-sensitive or case-insensitive search,
        /// and using word or ordinal comparison rules.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty string, which will
        /// always return 0.
        /// <para/>
        /// If <paramref name="startIndex"/> is less than zero, it is treated as zero. If it is greater
        /// than <see cref="Length"/>, it is treated as equal to <see cref="Length"/>.
        /// <para/>
        /// On older platforms than .NET Core, this overload provides optimizations for
        /// <see cref="StringComparison.OrdinalIgnoreCase"/> over and above the System.Memory package.
        /// </remarks>
        public int IndexOf(string value, int startIndex, StringComparison comparisonType)
        {
            lock (syncRoot)
            {
                return buffer.IndexOf(value, startIndex, comparisonType);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the first occurrence of the specified span beginning
        /// at the specified index in this instance.
        /// </summary>
        /// <param name="value">The span to find.</param>
        /// <param name="startIndex">The search starting position.</param>
        /// <param name="comparisonType">
        /// One of the enumeration values that determines how the current instance
        /// and <paramref name="value"/> are compared.
        /// </param>
        /// <returns>
        /// The zero-based index position of <paramref name="value"/> from the start of
        /// the current instance if that sequence of characters is found, or -1 if it is not.
        /// If <paramref name="value"/> is empty, the return value is the effective start index
        /// after clamping.
        /// </returns>
        /// <exception cref="ArgumentException">
        /// <paramref name="comparisonType"/> is not a
        /// <see cref="StringComparison"/> value.
        /// </exception>
        /// <remarks>
        /// Index numbering starts from zero. The <paramref name="startIndex"/> parameter is clamped to
        /// the valid range of the current instance. Values less than zero are treated as zero, and values
        /// greater than <see cref="Length" /> are treated as equal to <see cref="Length" />.
        /// If <paramref name="startIndex"/> equals <see cref="Length" />, this method
        /// returns -1 for non-empty searches. If <paramref name="value"/> is empty, this method returns
        /// the effective start index after clamping.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is considered
        /// equivalent to another character only if their Unicode scalar values are the same.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty span, which will
        /// always return 0.
        /// <para/>
        /// If <paramref name="startIndex"/> is less than zero, it is treated as zero. If it is greater
        /// than <see cref="Length"/>, it is treated as equal to <see cref="Length"/>.
        /// <para/>
        /// On older platforms than .NET Core, this overload provides optimizations for
        /// <see cref="StringComparison.OrdinalIgnoreCase"/> over and above the System.Memory package.
        /// </remarks>
        public int IndexOf(ReadOnlySpan<char> value, int startIndex, StringComparison comparisonType)
        {
            lock (syncRoot)
            {
                return buffer.IndexOf(value, startIndex, comparisonType);
            }
        }

        /// <summary>
        /// Reports the zero-based index position of the last occurrence of a specified Unicode character
        /// within this instance.
        /// </summary>
        /// <param name="value">The Unicode character to seek.</param>
        /// <returns>
        /// The zero-based index of the last occurrence of the value in the
        /// span. If not found, returns -1.
        /// </returns>
        /// <remarks>
        /// Index numbering starts from zero. That is, the first character in the current instance
        /// is at index zero and the last is at <see cref="Length"/> - 1.
        /// <para/>
        /// This method begins searching at the last character position of this instance
        /// and proceeds backward toward the beginning until either <paramref name="value"/>
        /// is found or the first character position has been examined. The search is case-sensitive.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is
        /// considered equivalent to another character only if their Unicode scalar values are
        /// the same.
        /// </remarks>
        public int LastIndexOf(char value)
        {
            lock (syncRoot)
            {
                return buffer.LastIndexOf(value);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the last occurrence of the specified string in
        /// this instance.
        /// </summary>
        /// <param name="value">The string to find.</param>
        /// <returns>
        /// The zero-based starting index position of value if that string is found, or -1
        /// if it is not found. If <paramref name="value"/> is <see cref="string.Empty"/>,
        /// it returns <see cref="Length"/>.
        /// </returns>
        /// <exception cref="ArgumentNullException"><paramref name="value"/> is <see langword="null"/>.</exception>
        /// <remarks>
        /// Index numbering starts from zero. That is, the first character in the current instance
        /// is at index zero and the last is at <see cref="Length"/> - 1.
        /// <para/>
        /// This method begins searching at the last character position of this instance
        /// and proceeds backward toward the beginning until either <paramref name="value"/>
        /// is found or the first character position has been examined. The search is case-sensitive.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is
        /// considered equivalent to another character only if their Unicode scalar values are
        /// the same.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty string, which will
        /// always return <see cref="Length"/>.
        /// </remarks>
        public int LastIndexOf(string value)
        {
            lock (syncRoot)
            {
                return buffer.LastIndexOf(value);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the last occurrence of the specified string in
        /// this instance.
        /// </summary>
        /// <param name="value">The span to find.</param>
        /// <returns>
        /// The zero-based starting index position of value if that span is found, or -1
        /// if it is not found. If <paramref name="value"/> is <see cref="ReadOnlySpan{Char}.Empty"/>,
        /// it returns <see cref="Length"/>.
        /// </returns>
        /// <remarks>
        /// Index numbering starts from zero. That is, the first character in the current instance
        /// is at index zero and the last is at <see cref="Length"/> - 1.
        /// <para/>
        /// This method begins searching at the last character position of this instance
        /// and proceeds backward toward the beginning until either <paramref name="value"/>
        /// is found or the first character position has been examined. The search is case-sensitive.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is
        /// considered equivalent to another character only if their Unicode scalar values are
        /// the same.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty span, which will
        /// always return <see cref="Length"/>.
        /// </remarks>
        public int LastIndexOf(ReadOnlySpan<char> value)
        {
            lock (syncRoot)
            {
                return buffer.LastIndexOf(value);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the last occurrence of the specified string beginning
        /// at the specified index in this instance.
        /// </summary>
        /// <param name="value">The string to find.</param>
        /// <param name="startIndex">
        /// The search starting position. The search proceeds from
        /// <paramref name="startIndex"/> toward the beginning of this instance.
        /// </param>
        /// <returns>
        /// The zero-based starting index position of value if that string is found, or -1
        /// if it is not found. If <paramref name="value"/> is <see cref="string.Empty"/>,
        /// it returns <paramref name="startIndex"/> if it is within the bounds of the current instance; otherwise,
        /// if <paramref name="startIndex"/> is greater than <see cref="Length"/>, it
        /// returns <see cref="Length"/>.
        /// </returns>
        /// <exception cref="ArgumentNullException"><paramref name="value"/> is <see langword="null"/>.</exception>
        /// <remarks>
        /// Index numbering starts from zero. That is, the first character in the current instance
        /// is at index zero and the last is at <see cref="Length"/> - 1.
        /// <para/>
        /// The search begins at the effective starting position and proceeds backward until either
        /// <paramref name="value"/> is found or the first character position has been examined.
        /// The effective starting position is the lesser of <paramref name="startIndex"/> and
        /// <see cref="Length"/> - <paramref name="value"/>.Length. For example, if
        /// <paramref name="startIndex"/> is <see cref="Length"/> - 1 and <paramref name="value"/>
        /// contains a single character, the method searches every character from the last
        /// character in the string to the beginning. The search is case-sensitive.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is
        /// considered equivalent to another character only if their Unicode scalar values are
        /// the same.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty string, which will
        /// always return the lesser of <paramref name="startIndex"/> or <see cref="Length"/>.
        /// <para/>
        /// If <paramref name="startIndex"/> is less than zero, the method returns -1. If it is greater than
        /// <see cref="Length"/>, it is treated as equal to <see cref="Length"/>.
        /// </remarks>
        public int LastIndexOf(string value, int startIndex)
        {
            lock (syncRoot)
            {
                return buffer.LastIndexOf(value, startIndex);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the last occurrence of the specified span beginning
        /// at the specified index in this instance.
        /// </summary>
        /// <param name="value">The span to find.</param>
        /// <param name="startIndex">
        /// The search starting position. The search proceeds from startIndex toward the
        /// beginning of this instance.
        /// </param>
        /// <returns>
        /// The zero-based starting index position of value if that span is found, or -1
        /// if it is not found. If <paramref name="value"/> is <see cref="ReadOnlySpan{Char}.Empty"/>,
        /// it returns <paramref name="startIndex"/> if it is within the bounds of the current instance; otherwise,
        /// if <paramref name="startIndex"/> is greater than <see cref="Length"/>, it
        /// returns <see cref="Length"/>.
        /// </returns>
        /// <remarks>
        /// Index numbering starts from zero. That is, the first character in the current instance
        /// is at index zero and the last is at <see cref="Length"/> - 1.
        /// <para/>
        /// The search begins at the effective starting position and proceeds backward until either
        /// <paramref name="value"/> is found or the first character position has been examined.
        /// The effective starting position is the lesser of <paramref name="startIndex"/> and
        /// <see cref="Length"/> - <paramref name="value"/>.Length. For example, if
        /// <paramref name="startIndex"/> is <see cref="Length"/> - 1 and <paramref name="value"/>
        /// contains a single character, the method searches every character from the last
        /// character in the string to the beginning. The search is case-sensitive.
        /// <para/>
        /// This method performs an ordinal (culture-insensitive) search, where a character is
        /// considered equivalent to another character only if their Unicode scalar values are
        /// the same.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty span, which will
        /// always return the lesser of <paramref name="startIndex"/> or <see cref="Length"/>.
        /// <para/>
        /// If <paramref name="startIndex"/> is less than zero, the method returns -1. If it is greater than
        /// <see cref="Length"/>, it is treated as equal to <see cref="Length"/>.
        /// </remarks>
        public int LastIndexOf(ReadOnlySpan<char> value, int startIndex)
        {
            lock (syncRoot)
            {
                return buffer.LastIndexOf(value, startIndex);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the last occurrence of the specified string in the
        /// this instance.
        /// </summary>
        /// <param name="value">The string to find.</param>
        /// <param name="comparisonType">
        /// One of the enumeration values that determines how the current instance
        /// and <paramref name="value"/> are compared.
        /// </param>
        /// <returns>
        /// The zero-based starting index position of value if that string is found, or -1
        /// if it is not found. If <paramref name="value"/> is <see cref="string.Empty"/>,
        /// it returns <see cref="Length"/>.
        /// </returns>
        /// <exception cref="ArgumentNullException"><paramref name="value"/> is <see langword="null"/>.</exception>
        /// <exception cref="ArgumentException">
        /// <paramref name="comparisonType"/> is not a
        /// <see cref="StringComparison"/> value.
        /// </exception>
        /// <remarks>
        /// Index numbering starts from zero. That is, the first character in the current instance
        /// is at index zero and the last is at <see cref="Length"/> - 1.
        /// <para/>
        /// This method begins searching at the last character position of this instance
        /// and proceeds backward toward the beginning until either <paramref name="value"/>
        /// is found or the first character position has been examined.
        /// <para/>
        /// The <paramref name="comparisonType"/> parameter specifies to search for the <paramref name="value"/>
        /// parameter using the current or invariant culture, using a case-sensitive or case-insensitive search,
        /// and using word or ordinal comparison rules.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty string, which will
        /// always return <see cref="Length"/>.
        /// <para/>
        /// On older platforms than .NET Core, this overload provides optimizations for
        /// <see cref="StringComparison.OrdinalIgnoreCase"/> over and above the System.Memory package.
        /// </remarks>
        public int LastIndexOf(string value, StringComparison comparisonType)
        {
            lock (syncRoot)
            {
                return buffer.LastIndexOf(value, comparisonType);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the last occurrence of the specified span in the
        /// this instance.
        /// </summary>
        /// <param name="value">The span to find.</param>
        /// <param name="comparisonType">
        /// One of the enumeration values that determines how the current instance
        /// and <paramref name="value"/> are compared.
        /// </param>
        /// <returns>
        /// The zero-based starting index position of value if that span is found, or -1
        /// if it is not found. If <paramref name="value"/> is <see cref="ReadOnlySpan{Char}.Empty"/>,
        /// it returns <see cref="Length"/>.
        /// </returns>
        /// <exception cref="ArgumentException">
        /// <paramref name="comparisonType"/> is not a
        /// <see cref="StringComparison"/> value.
        /// </exception>
        /// <remarks>
        /// Index numbering starts from zero. That is, the first character in the current instance
        /// is at index zero and the last is at <see cref="Length"/> - 1.
        /// <para/>
        /// This method begins searching at the last character position of this instance
        /// and proceeds backward toward the beginning until either <paramref name="value"/>
        /// is found or the first character position has been examined.
        /// <para/>
        /// The <paramref name="comparisonType"/> parameter specifies to search for the <paramref name="value"/>
        /// parameter using the current or invariant culture, using a case-sensitive or case-insensitive search,
        /// and using word or ordinal comparison rules.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty span, which will
        /// always return <see cref="Length"/>.
        /// <para/>
        /// On older platforms than .NET Core, this overload provides optimizations for
        /// <see cref="StringComparison.OrdinalIgnoreCase"/> over and above the System.Memory package.
        /// </remarks>
        public int LastIndexOf(ReadOnlySpan<char> value, StringComparison comparisonType)
        {
            lock (syncRoot)
            {
                return buffer.LastIndexOf(value, comparisonType);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the last occurrence of the specified string beginning
        /// at the specified index in this instance.
        /// </summary>
        /// <param name="value">The string to find.</param>
        /// <param name="startIndex">
        /// The search starting position. The search proceeds from <paramref name="startIndex"/> toward the
        /// beginning of this instance.
        /// </param>
        /// <param name="comparisonType">
        /// One of the enumeration values that determines how the current instance
        /// and <paramref name="value"/> are compared.
        /// </param>
        /// <returns>
        /// The zero-based starting index position of value if that string is found, or -1
        /// if it is not found. If <paramref name="value"/> is <see cref="string.Empty"/>,
        /// it returns <paramref name="startIndex"/> if it is within the bounds of the the current instance; otherwise, if
        /// <paramref name="startIndex"/> is greater than <see cref="Length"/>, it returns
        /// the <see cref="Length"/>.
        /// </returns>
        /// <exception cref="ArgumentNullException"><paramref name="value"/> is <see langword="null"/>.</exception>
        /// <exception cref="ArgumentException">
        /// <paramref name="comparisonType"/> is not a
        /// <see cref="StringComparison"/> value.
        /// </exception>
        /// <remarks>
        /// Index numbering starts from zero. That is, the first character in the current instance
        /// is at index zero and the last is at <see cref="Length"/> - 1.
        /// <para/>
        /// The search begins at the effective starting position and proceeds backward until either
        /// <paramref name="value"/> is found or the first character position has been examined.
        /// The effective starting position is the lesser of <paramref name="startIndex"/> and
        /// <see cref="Length"/> - <paramref name="value"/>.Length. For example, if
        /// <paramref name="startIndex"/> is <see cref="Length"/> - 1 and <paramref name="value"/>
        /// contains a single character, the method searches every character from the last
        /// character in the string to the beginning.
        /// <para/>
        /// The <paramref name="comparisonType"/> parameter specifies to search for the <paramref name="value"/>
        /// parameter using the current or invariant culture, using a case-sensitive or case-insensitive search,
        /// and using word or ordinal comparison rules.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty string, which will
        /// always return the lesser of <paramref name="startIndex"/> or <see cref="Length"/>.
        /// <para/>
        /// If <paramref name="startIndex"/> is less than zero, the method returns -1. If it is greater than
        /// <see cref="Length"/>, it is treated as equal to <see cref="Length"/>.
        /// <para/>
        /// On older platforms than .NET Core, this overload provides optimizations for
        /// <see cref="StringComparison.OrdinalIgnoreCase"/> over and above the System.Memory package.
        /// </remarks>
        public int LastIndexOf(string value, int startIndex, StringComparison comparisonType)
        {
            lock (syncRoot)
            {
                return buffer.LastIndexOf(value, startIndex, comparisonType);
            }
        }

        /// <summary>
        /// Reports the zero-based index of the last occurrence of the specified span  beginning
        /// at the specified index in this instance.
        /// </summary>
        /// <param name="value">The span to find.</param>
        /// <param name="startIndex">
        /// The search starting position. The search proceeds from <paramref name="startIndex"/> toward the
        /// beginning of this instance.
        /// </param>
        /// <param name="comparisonType">
        /// One of the enumeration values that determines how the current instance
        /// and <paramref name="value"/> are compared.
        /// </param>
        /// <returns>
        /// The zero-based starting index position of value if that span is found, or -1
        /// if it is not found. If <paramref name="value"/> is <see cref="ReadOnlySpan{Char}.Empty"/>,
        /// it returns <paramref name="startIndex"/> if it is within the bounds of the the current instance; otherwise, if
        /// <paramref name="startIndex"/> is greater than <see cref="Length"/>, it returns
        /// the <see cref="Length"/>.
        /// </returns>
        /// <exception cref="ArgumentException">
        /// <paramref name="comparisonType"/> is not a
        /// <see cref="StringComparison"/> value.
        /// </exception>
        /// <remarks>
        /// Index numbering starts from zero. That is, the first character in the current instance
        /// is at index zero and the last is at <see cref="Length"/> - 1.
        /// <para/>
        /// The search begins at the effective starting position and proceeds backward until either
        /// <paramref name="value"/> is found or the first character position has been examined.
        /// The effective starting position is the lesser of <paramref name="startIndex"/> and
        /// <see cref="Length"/> - <paramref name="value"/>.Length. For example, if
        /// <paramref name="startIndex"/> is <see cref="Length"/> - 1 and <paramref name="value"/>
        /// contains a single character, the method searches every character from the last
        /// character in the string to the beginning.
        /// <para/>
        /// The <paramref name="comparisonType"/> parameter specifies to search for the <paramref name="value"/>
        /// parameter using the current or invariant culture, using a case-sensitive or case-insensitive search,
        /// and using word or ordinal comparison rules.
        /// <para/>
        /// To match the behavior of the JDK, this method allows searches for the empty span, which will
        /// always return the lesser of <paramref name="startIndex"/> or <see cref="Length"/>.
        /// <para/>
        /// If <paramref name="startIndex"/> is less than zero, the method returns -1. If it is greater than
        /// <see cref="Length"/>, it is treated as equal to <see cref="Length"/>.
        /// <para/>
        /// On older platforms than .NET Core, this overload provides optimizations for
        /// <see cref="StringComparison.OrdinalIgnoreCase"/> over and above the System.Memory package.
        /// </remarks>
        public int LastIndexOf(ReadOnlySpan<char> value, int startIndex, StringComparison comparisonType)
        {
            lock (syncRoot)
            {
                return buffer.LastIndexOf(value, startIndex, comparisonType);
            }
        }

    }
}
