//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     Instead of editing this file, the MutableTextBufferExtensions*.cs files should be edited
//     which will propagate the edits to this file.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using J2N.CodeGeneration;
using J2N.Numerics;
using J2N.Text;
using System;
using System.Runtime.CompilerServices;

namespace J2N
{
    public static partial class SynchronizedTextBuilderExtensions
    {
        /// <summary>
        /// Appends the string representation of a specified object to this instance using the specified format
        /// and culture-specific format information.
        /// </summary>
        /// <typeparam name="TBuilder">The type of the target builder.</typeparam>
        /// <param name="text">The target builder.</param>
        /// <param name="value">The object to append.</param>
        /// <param name="format">A standard or custom format string.</param>
        /// <param name="provider">An object that supplies culture-specific formatting information.</param>
        /// <returns>A reference to this instance after the operation has completed.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="text"/> is <see langword="null"/></exception>
        /// <remarks>
        /// <paramref name="format"/> and <paramref name="provider"/> are only applied if the object implements <see cref="ISpanFormattable"/>,
        /// <see cref="IFormattable"/>, <c>IStructuralFormattable</c>, or subclasses <see cref="Number"/>.
        /// <para/>
        /// The capacity of this instance is adjusted as needed.
        /// <para/>
        /// <b>Notes to Callers</b>
        /// <para/>
        /// When you instantiate a <see cref="SynchronizedTextBuilder"/> object by calling <see cref="SynchronizedTextBuilder(int, int)"/>,
        /// both the length and the capacity of the <see cref="SynchronizedTextBuilder"/> instance can grow beyond
        /// the value of its <see cref="SynchronizedTextBuilder.MaxCapacity"/> property. This can occur particularly when you call the <see cref="J2N.Text.SynchronizedTextBuilderExtensions.Append{TBuilder}(TBuilder, string?)"/>
        /// and <see cref="J2N.Text.SynchronizedTextBuilderExtensions.AppendFormat{TBuilder}(TBuilder, string, object?)"/> methods to append small strings.
        /// </remarks>
        /// <seealso cref="object" />
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TBuilder Append<TBuilder>(this TBuilder text, object? value, string? format = null, IFormatProvider? provider = null)
            where TBuilder : SynchronizedTextBuilder
        {
            if (text is null)
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.text);

            lock (text.SyncRoot)
            {
                text.buffer.AppendInternal(value, format, provider);
                return text;
            }
        }

        /// <summary>Inserts the string representation of an object into this instance at the specified character position.</summary>
        /// <typeparam name="TBuilder">The type of the target builder.</typeparam>
        /// <param name="text">The target builder.</param>
        /// <param name="index">The position in this instance where insertion begins.</param>
        /// <param name="value">The object to insert, or <see langword="null"/>.</param>
        /// <param name="format">A standard or custom format string.</param>
        /// <param name="provider">An object that supplies culture-specific formatting information.</param>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="text"/> is <see langword="null"/></exception>
        /// <exception cref="ArgumentOutOfRangeException"><paramref name="index"/> is less than zero or greater than the current length of this instance.</exception>
        /// <exception cref="OutOfMemoryException">Enlarging the value of this instance would exceed <see cref="SynchronizedTextBuilder.MaxCapacity"/>.</exception>
        /// <remarks>
        /// <paramref name="format"/> and <paramref name="provider"/> are only applied if the object implements <see cref="ISpanFormattable"/>,
        /// <see cref="IFormattable"/>, <c>IStructuralFormattable</c>, or subclasses <see cref="Number"/>.
        /// <para/>
        /// Existing characters are shifted to make room for the new text. The capacity of this instance is adjusted as needed.
        /// <para/>
        /// If <paramref name="value"/> is <see langword="null"/>, the <see cref="SynchronizedTextBuilder"/> is not changed.
        /// </remarks>
        /// <seealso cref="object" />
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TBuilder Insert<TBuilder>(this TBuilder text, int index, object? value, string? format = null, IFormatProvider? provider = null)
            where TBuilder : SynchronizedTextBuilder
        {
            if (text is null)
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.text);

            lock (text.SyncRoot)
            {
                text.buffer.InsertInternal(index, value, format, provider);
                return text;
            }
        }

    }
}
